### ISSUE TITLE
Read only volumes

### ISSUE THREAD

**Issue by ediskandarov-cur** [UKHomeOffice/docker-logstash-kubernetes#15]
README file says that only `/var/log/journal` should be mounted in container with read only mode.

```
$ docker run -ti --rm \
    -v /var/lib/logstash-kubernetes:/var/lib/logstash \
    -v /var/log/journal:/var/log/journal:ro \
    -v /var/lib/docker/containers:/var/lib/docker/containers \
    -v /var/log/containers:/var/log/containers \
    -e ELASTICSEARCH_HOST=my-est-host.local:9200 \
    quay.io/ukhomeofficedigital/logstash-kubernetes:v0.1.0
```

`-v /var/lib/logstash-kubernetes:/var/lib/logstash` - this volume is required by sincedb

Is there any reason to mount following volumes in read/write mode?

```
    -v /var/lib/docker/containers:/var/lib/docker/containers \
    -v /var/log/containers:/var/log/containers \
```

**Comment by vaijab** [comment]
> Is there any reason to mount following volumes in read/write mode?
> 
> ```
> -v /var/lib/docker/containers:/var/lib/docker/containers \
> -v /var/log/containers:/var/log/containers \
> ```

You're right, there is no reason to mount those volumes in rw mode. Would be great if you could raise a PR to fix the readme. Thanks.
