### ISSUE TITLE
Pros and cons vs fluentd

### ISSUE THREAD

**Issue by roflmao** [UKHomeOffice/docker-logstash-kubernetes#9]
Whats the real difference vs fluentd sidecar examples which kubernetes 'recommends'?

**Comment by vaijab** [comment]
@roflmao It is hard to say. I guess pros and cons depend on a specific use case.

I found fluentd not flexible enough for us. This particular docker image pulls logs from systemd journal as well as kubernetes. Also log events are transformed to work with cloudwatch logs.

**Comment by ediskandarov-cur** [comment]
@roflmao I found that `fluentd-es` bundled with kubernetes due to bug in fluentd doesn't support sub-second precision.

With this plugin kibana displays log records with ms precision. It isn't enough for logging however it's the best elasticsearch 4 can do.
